import type { GetServerSideProps } from 'next';

import Head from 'next/head';

import { validateUser } from '@/services/library/validate-user';

import Signup from '@/app/layouts/Auth/Signup';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // const user = await validateUser(ctx);

  // if (!!user) {
  //   return {
  //     redirect: {
  //       destination: '/dashboard',
  //       permanent: false,
  //     },
  //     props: {},
  //   };
  // }

  return {
    props: {},
  };
};

export default function SignupPage() {
  return (
    <>
      <Head>
        <title>Cadastro</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/assets/logo-icon.png" />
      </Head>
      <Signup />
    </>
  );
}
