import Head from 'next/head';

import { Meme } from '@/app/layouts/Home/Room/Meme';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Meme Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Meme />
    </>
  );
}
