import Head from 'next/head';

import { HowToPlay } from '@/app/layouts/Home/HowToPlay';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Como Jogar?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HowToPlay />
    </>
  );
}
